### ISSUE TITLE
[vite]: Rollup failed to reoslve import "js-yaml" during npm run build

### ISSUE THREAD

**Issue by misslivirose** [mozilla/langview#2]
Fresh clone, followed instructions in the readme. When I run `npm run build`, I get the following error: 
```
[vite]: Rollup failed to resolve import "js-yaml" from "/home/ori/GitHub/langview/components/web-components/src/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "js-yaml" from "/home/ori/GitHub/langview/components/web-components/src/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/ori/GitHub/langview/demo/node_modules/vite/dist/node/chunks/dep-abb4f102.js:48051:27)
    at onRollupWarning (file:///home/ori/GitHub/langview/demo/node_modules/vite/dist/node/chunks/dep-abb4f102.js:48083:9)
    at onwarn (file:///home/ori/GitHub/langview/demo/node_modules/vite/dist/node/chunks/dep-abb4f102.js:47814:13)
    at file:///home/ori/GitHub/langview/demo/node_modules/rollup/dist/es/shared/node-entry.js:24070:13
    at Object.logger [as onLog] (file:///home/ori/GitHub/langview/demo/node_modules/rollup/dist/es/shared/node-entry.js:25742:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/ori/GitHub/langview/demo/node_modules/rollup/dist/es/shared/node-entry.js:24656:26)
    at file:///home/ori/GitHub/langview/demo/node_modules/rollup/dist/es/shared/node-entry.js:24616:26
```

I have verified that I have the correct versions of `js-yaml` and `vite` as specified in the codebase. New to Vite, so may be missing some prerequisites. .

Running Pop!_OS.

**Comment by moz-gh** [comment]
Great find - there appears to be a missing step in the README  for getting the demo up and running.
In the terminal (in the root of the project directory), before anything else, you'll need to run in order:
    ```cd /components/web-components```
    ```npm install```
   ```cd ../../demo```
    ```npm install```
    ```npm run build or npm run dev ```
